### ISSUE TITLE
Question about typescript versions 😄 

### ISSUE THREAD

**Issue by sourcec0de** [clarkmcc/go-typescript#1]
First of all, this is REALLY helpful!!!
Thank you for taking the time to build this awesome library!

My question is around how you acquired the typescript files in the versions directory.
I was following a [thread on goja][goja] and it seems like these files are a minified version of [typescripServices.js][tss]. Did you do anything special to compress/minify them so they work with goja? I couldn't get it to work out of the box.

Again, thank you for the hard work! 🚀

[goja]: https://github.com/dop251/goja/issues/3
[tss]: https://raw.githubusercontent.com/Microsoft/TypeScript/master/lib/typescriptServices.js

**Comment by clarkmcc** [comment]
No problem! I didn't do anything special actually, I just minified them using https://jscompress.com/. If that doesn't work for you, send an example of how you're loading the version into goja and I can take a look.
