### ISSUE TITLE
Have you considered integrating esbuild into it?

### ISSUE THREAD

**Issue by sohaha** [clarkmcc/go-typescript#11]
Great project!

**Comment by clarkmcc** [comment]
Thanks! Can you elaborate on what you mean by integrating esbuild, I'm not sure that I'm catching the vision? As I understand it, esbuild is a bundler for large Javascript projects, whereas this is just a Typescript runtime for using Typescript as a scripting language, so I'm not sure how much of an overlap would exist.

**Comment by clarkmcc** [comment]
Closing since I haven't heard back. Feel free to re-open if you'd like to continue the discussion.
